version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: ${APP_NAME}_redis

  postgres:
    image: library/postgres:alpine
    container_name: ${APP_NAME}_postgres
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5432:5432 # если надо подключяться снаружи (не из докера)

  mysql:
    image: mysql:5.7.39-debian
    container_name: ${APP_NAME}_mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306 # если надо подключяться снаружи (не из докера)

  nginx:
    image: library/nginx:alpine
    container_name: ${APP_NAME}_nginx
    ports:
      # For access server at localhost:${WEB_SERVER_PORT}
      - ${WEB_SERVER_PORT}:80
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www/html'

  php:
    build: ./docker/php
    container_name: ${APP_NAME}_php
    ports:
      - 9000:9000
    volumes:
      - './src:/var/www/html'
