version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: ${APP_NAME}_redis

  postgres:
    image: library/postgres:alpine
    container_name: ${APP_NAME}_postgres
    volumes:
      - ./docker/postgres:${PGDATA_PATH}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA_PATH}/pgdata
    ports:
      - 5432:5432
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  nginx:
    image: library/nginx:alpine
    container_name: ${APP_NAME}_nginx
    ports:
      # For access server at localhost:${WEB_SERVER_PORT}
      - ${WEB_SERVER_PORT}:80
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www/html'
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  php:
    image: ${APP_NAME}-php
    build: ./docker/php
    container_name: ${APP_NAME}_php
    ports:
      - 9000:9000
    volumes:
      - './src:/var/www/html'
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
